"""GetSongBPM fallback client.

Used only when ReccoBeats misses. Looks up by artist + title (fuzzy);
returns BPM and key only. Audio-feature columns stay empty.

Free API requires registration + a public backlink to getsongbpm.com.
This project includes the attribution in scripts/README.md and
taste/profile.md (when generated by Subsystem #7).
"""

from typing import Optional

import requests

from enrich.models import EnrichmentResult

GETSONGBPM_BASE_URL = "https://api.getsongbpm.com"
_DEFAULT_TIMEOUT_S = 10

# Map GetSongBPM's "key_of" string format ("F# minor", "C major") to
# (key_int, mode_int) pairs that match the camelot lookup.
_KEY_TO_INT = {
    "C": 0, "C#": 1, "Db": 1, "D": 2, "D#": 3, "Eb": 3,
    "E": 4, "F": 5, "F#": 6, "Gb": 6, "G": 7, "G#": 8, "Ab": 8,
    "A": 9, "A#": 10, "Bb": 10, "B": 11,
}


def _parse_key_of(key_of: str) -> tuple[Optional[int], Optional[int]]:
    """Parse 'F# minor' / 'C major' into (key_int, mode_int)."""
    if not key_of:
        return None, None
    parts = key_of.strip().split()
    if len(parts) != 2:
        return None, None
    pitch, mode_str = parts[0], parts[1].lower()
    key_int = _KEY_TO_INT.get(pitch)
    mode_int = 1 if mode_str.startswith("major") else 0 if mode_str.startswith("minor") else None
    return key_int, mode_int


def fetch(artist: str, title: str, api_key: str) -> Optional[EnrichmentResult]:
    if not api_key:
        raise ValueError("api_key required for GetSongBPM")

    response = requests.get(
        f"{GETSONGBPM_BASE_URL}/search/",
        params={
            "type": "both",
            "lookup": f"song:{title}+artist:{artist}",
            "api_key": api_key,
        },
        timeout=_DEFAULT_TIMEOUT_S,
    )
    response.raise_for_status()
    payload = response.json()

    matches = payload.get("search", []) if isinstance(payload, dict) else []
    if not matches:
        return None

    # Defensive artist match — reject if GetSongBPM returns a different artist.
    first = matches[0]
    returned_artist = (first.get("artist") or {}).get("name", "")
    if returned_artist.strip().lower() != artist.strip().lower():
        return None

    tempo_str = first.get("tempo", "")
    try:
        bpm = float(tempo_str) if tempo_str else None
    except (TypeError, ValueError):
        bpm = None

    key_int, mode_int = _parse_key_of(first.get("key_of", ""))

    return EnrichmentResult(bpm=bpm, key_int=key_int, mode=mode_int)
